import json
import os
from datetime import datetime, timedelta
from pathlib import Path

class MoonshotUsageTracker:
    def __init__(self):
        self.data_file = Path.home() / ".openclaw" / "workspace" / "moonshot_usage.json"
        self.data_file.parent.mkdir(parents=True, exist_ok=True)
        
        # Pricing in USD (as of Feb 2026)
        self.PRICE_PER_1K_TOKENS = 0.0008  # ~$0.0008 USD per 1K tokens
        
        self.load_data()
    
    def load_data(self):
        """Load usage data from file"""
        if self.data_file.exists():
            with open(self.data_file, 'r') as f:
                self.data = json.load(f)
        else:
            self.data = {
                "sessions": [],
                "total_input_tokens": 0,
                "total_output_tokens": 0,
                "total_cost_usd": 0,
                "created_at": datetime.now().isoformat()
            }
    
    def save_data(self):
        """Save usage data to file"""
        with open(self.data_file, 'w', encoding='utf-8') as f:
            json.dump(self.data, f, indent=2)
    
    def log_session(self, input_tokens: int, output_tokens: int, session_type: str = "chat"):
        """Log a session's token usage"""
        session_cost = self.calculate_cost(input_tokens, output_tokens)
        
        session = {
            "timestamp": datetime.now().isoformat(),
            "type": session_type,
            "input_tokens": input_tokens,
            "output_tokens": output_tokens,
            "cost_usd": round(session_cost, 6)
        }
        
        self.data["sessions"].append(session)
        self.data["total_input_tokens"] += input_tokens
        self.data["total_output_tokens"] += output_tokens
        self.data["total_cost_usd"] += session_cost
        
        self.save_data()
        return session_cost
    
    def calculate_cost(self, input_tokens: int, output_tokens: int) -> float:
        """Calculate cost in USD"""
        total_tokens = input_tokens + output_tokens
        cost = (total_tokens / 1000) * self.PRICE_PER_1K_TOKENS
        return cost
    
    def get_daily_report(self, days: int = 1) -> dict:
        """Get usage report for last N days"""
        cutoff = datetime.now() - timedelta(days=days)
        
        sessions = [
            s for s in self.data["sessions"]
            if datetime.fromisoformat(s["timestamp"]) > cutoff
        ]
        
        total_input = sum(s["input_tokens"] for s in sessions)
        total_output = sum(s["output_tokens"] for s in sessions)
        total_cost = sum(s["cost_usd"] for s in sessions)
        
        return {
            "period": f"Last {days} day(s)",
            "sessions_count": len(sessions),
            "input_tokens": total_input,
            "output_tokens": total_output,
            "total_tokens": total_input + total_output,
            "cost_usd": round(total_cost, 4),
            "cost_formatted": f"${total_cost:.4f} USD"
        }
    
    def get_weekly_report(self) -> dict:
        """Get weekly usage report"""
        return self.get_daily_report(days=7)
    
    def get_monthly_report(self) -> dict:
        """Get monthly usage report"""
        return self.get_daily_report(days=30)
    
    def generate_markdown_report(self, days: int = 1) -> str:
        """Generate a markdown report for Obsidian"""
        report = self.get_daily_report(days)
        
        md = f"""# Moonshot Usage Report

**Generated:** {datetime.now().strftime("%Y-%m-%d %H:%M")}
**Period:** {report['period']}

## 📊 Summary

| Metric | Value |
|--------|-------|
| **Sessions** | {report['sessions_count']} |
| **Input Tokens** | {report['input_tokens']:,} |
| **Output Tokens** | {report['output_tokens']:,} |
| **Total Tokens** | {report['total_tokens']:,} |
| **Cost** | **{report['cost_formatted']}** |

## 💰 Cost Breakdown

- Rate: $0.0008 per 1K tokens
- Input cost: ${(report['input_tokens'] / 1000 * 0.0008):.4f}
- Output cost: ${(report['output_tokens'] / 1000 * 0.0008):.4f}

## 📈 All-Time Stats

- Total Sessions: {len(self.data['sessions'])}
- Total Input: {self.data['total_input_tokens']:,} tokens
- Total Output: {self.data['total_output_tokens']:,} tokens
- **Total Spent: ${self.data['total_cost_usd']:.4f} USD**

---

*Auto-generated by Gotchi Usage Tracker*
"""
        return md
    
    def save_report_to_obsidian(self, days: int = 1):
        """Save report to Obsidian vault"""
        report_md = self.generate_markdown_report(days)
        
        obsidian_path = Path.home() / "Documents" / "Obsidian Vault" / "GotchiBrain"
        obsidian_path.mkdir(parents=True, exist_ok=True)
        
        report_file = obsidian_path / f"Moonshot Usage Report {datetime.now().strftime('%Y-%m-%d')}.md"
        
        with open(report_file, 'w', encoding='utf-8') as f:
            f.write(report_md)
        
        return str(report_file)

# Example usage
if __name__ == "__main__":
    tracker = MoonshotUsageTracker()
    
    # Log current session (example)
    # tracker.log_session(input_tokens=91000, output_tokens=138000)
    
    # Generate reports
    daily = tracker.get_daily_report(1)
    weekly = tracker.get_weekly_report()
    
    print("Daily Report:")
    print(f"  Cost: {daily['cost_formatted']}")
    print(f"  Tokens: {daily['total_tokens']:,}")
    
    print("\nWeekly Report:")
    print(f"  Cost: {weekly['cost_formatted']}")
    print(f"  Tokens: {weekly['total_tokens']:,}")
    
    # Save to Obsidian
    report_path = tracker.save_report_to_obsidian(1)
    print(f"\nReport saved to: {report_path}")
